名字: Netlib Keepalive

on:
  schedule:
    - cron: '0 9 */17 * *'  # 每30天运行一次（时间早上8点）
  workflow_dispatch:  # 允许手动运行

jobs:
  auto_login_netlib:
    runs-on: ubuntu-latest
    steps:
      - 名字: Checkout
        uses: actions/checkout@v4

      - 名字: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - 名字: Install dependencies
        run: npm install

      - 名字: Install Playwright and browser
        run: npx playwright install --with-deps chromium

      - 名字: Run lognin script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
        run: npm start
